apiVersion: 2
dataDisplay: {}
docs: {}
interfaceDefaults: {}
provenanceSpec:
  corpus: The Deipnosophistae by Athenaeus
  org: pthu
  relative: Athenaeus/Deipnosophistae/tf
  repo: athenaeus
  version: '1.1'
typeDisplay:
  #_book:
    # children: book
  p:
    # children: _sentence
    label: '{p}'
  word:
    featuresBare: beta_plain
writing: grc
